"""MCP transport for the agent-tool surface.

The actual tools live in `holonomy_lib.provenance.agent` — this module
just wraps them in FastMCP's stdio transport so they're callable from
any MCP client (Claude Desktop, mcp-cli, custom clients).

Each tool in `agent.list_tools()` is registered with FastMCP under
its name, with the `registry: ProvenanceRegistry` argument pre-bound
to the loaded registry. The LLM-facing tool surface therefore
matches the native-tool-use schema generated by
`agent.to_anthropic_schema()` / `agent.to_openai_schema()` — same
tools, different transports.

Entry point: `python -m holonomy_lib.provenance.mcp` reads the
registry path from `HOLONOMY_PROVENANCE_REGISTRY` and starts the
server on stdio (MCP's standard transport).

The MCP SDK (`mcp` package) is an optional dependency in the
`[mcp]` extras group. Importing this module without `mcp` installed
raises a clear ImportError that points to the install.

Limitations (v0.4):
- File-loaded registries only. Socket-attached / live-process mode
  is planned for v0.5.
- The registry is loaded once at server start; subsequent on-disk
  changes aren't visible until the server restarts.
"""

from __future__ import annotations

import inspect
import os
from functools import wraps
from pathlib import Path
from typing import Any

from holonomy_lib.provenance import agent
from holonomy_lib.provenance.protocol import ProvenanceRegistry

try:
    from mcp.server.fastmcp import FastMCP
except ImportError as e:
    raise ImportError(
        "holonomy_lib.provenance.mcp requires the `mcp` package. "
        "Install it via `pip install 'holonomy-lib[mcp]'`."
    ) from e


def _bind_registry(spec: agent.ToolSpec, registry: ProvenanceRegistry):
    """Build a closure that pre-binds the registry arg so the LLM-facing
    surface doesn't see it.

    Preserves the original function's signature *without* the registry
    parameter, so FastMCP can introspect it and generate the right
    tool schema. Annotations are substituted with the resolved type
    hints (from ToolSpec.type_hints) so pydantic — which FastMCP uses
    under the hood — can build models from `from __future__ import
    annotations` modules without trying to eval string annotations
    in the wrong scope.
    """
    fn = spec.fn
    sig = inspect.signature(fn)
    # Drop the `registry` parameter and replace stringified annotations
    # with resolved types.
    params = []
    for name, p in sig.parameters.items():
        if name == "registry":
            continue
        resolved = spec.type_hints.get(name, p.annotation)
        params.append(p.replace(annotation=resolved))
    # Resolve the return annotation too.
    return_annotation = spec.type_hints.get("return", sig.return_annotation)
    bound_sig = sig.replace(
        parameters=params, return_annotation=return_annotation,
    )

    @wraps(fn)
    def wrapper(*args, **kwargs):
        return fn(registry, *args, **kwargs)
    wrapper.__signature__ = bound_sig  # type: ignore[attr-defined]
    # Also overwrite __annotations__ so pydantic's introspection paths
    # see the resolved types directly (some paths use __annotations__,
    # not signature).
    wrapper.__annotations__ = {
        p.name: p.annotation for p in params
    }
    if return_annotation is not inspect.Signature.empty:
        wrapper.__annotations__["return"] = return_annotation
    wrapper.__doc__ = spec.docstring or spec.description
    wrapper.__name__ = spec.name
    return wrapper


def build_server(registry: ProvenanceRegistry) -> FastMCP:
    """Construct an MCP server bound to the given registry.

    Registers every tool from `agent.list_tools()` with FastMCP,
    pre-binding the registry argument. The registry is captured by
    closure; reloading requires building a new server.
    """
    server = FastMCP("holonomy-lib-provenance")
    for spec in agent.list_tools():
        bound = _bind_registry(spec, registry)
        # FastMCP's @tool() decorator registers the wrapper; calling it
        # directly is the equivalent of decorating with no args.
        server.tool(description=spec.description)(bound)
    return server


def _load_registry_from_env() -> ProvenanceRegistry:
    """Locate and load the registry pointed to by HOLONOMY_PROVENANCE_REGISTRY."""
    path = os.environ.get("HOLONOMY_PROVENANCE_REGISTRY")
    if not path:
        raise RuntimeError(
            "HOLONOMY_PROVENANCE_REGISTRY environment variable is not set. "
            "Point it at a JSON file written by ProvenanceRegistry.save() "
            "before starting the MCP server."
        )
    p = Path(path).expanduser().resolve()
    if not p.exists():
        raise FileNotFoundError(f"Registry file not found: {p}")
    return ProvenanceRegistry.load(p)


def main() -> None:
    """Entry point: load registry from env and start the stdio server."""
    registry = _load_registry_from_env()
    server = build_server(registry)
    server.run()


if __name__ == "__main__":
    main()
