"""MCP transport for the agent-tool surface.

The actual tools live in `holonomy_lib.provenance.agent` — this module
just wraps them in FastMCP's stdio transport so they're callable from
any MCP client (Claude Desktop, mcp-cli, custom clients).

Each tool in `agent.list_tools()` is registered with FastMCP under
its name, with the `registry: ProvenanceRegistry` argument pre-bound
to the loaded registry. The LLM-facing tool surface therefore
matches the native-tool-use schema generated by
`agent.to_anthropic_schema()` / `agent.to_openai_schema()` — same
tools, different transports.

Entry point: `python -m holonomy_lib.provenance.mcp` reads the
registry path from `HOLONOMY_PROVENANCE_REGISTRY` and starts the
server on stdio (MCP's standard transport).

The MCP SDK (`mcp` package) is an optional dependency in the
`[mcp]` extras group. Importing this module without `mcp` installed
raises a clear ImportError that points to the install.

Limitations (v0.4):
- File-loaded registries only. Socket-attached / live-process mode
  is planned for v0.5.
- The registry is loaded once at server start; subsequent on-disk
  changes aren't visible until the server restarts.
"""

from __future__ import annotations

import importlib
import inspect
import os
from functools import wraps
from pathlib import Path
from typing import Any

from holonomy_lib.provenance import agent
from holonomy_lib.provenance.protocol import ProvenanceRegistry

# Eagerly import every holonomy_lib submodule that defines decorated
# ops so OP_REGISTRY is populated before any tool gets called. Without
# this, a saved registry referencing e.g. `truncated_svd` would fail
# replay because the @with_provenance decoration only fires at import
# time and the server process doesn't otherwise touch those modules.
_OP_MODULES = (
    "holonomy_lib.algebra.linear",
    "holonomy_lib.algebra.lanczos",
    "holonomy_lib.spectral.laplacian",
    "holonomy_lib.spectral.magnetic",
    "holonomy_lib.spectral.heat_kernel",
    "holonomy_lib.spectral.eigenmaps",
    "holonomy_lib.spectral.resistance",
    "holonomy_lib.spectral.diffusion_map",
    "holonomy_lib.tensor_calculus.hosvd",
    "holonomy_lib.discrete_geometry.ricci",
    "holonomy_lib.discrete_geometry.forman",
    "holonomy_lib.discrete_geometry.flow",
    "holonomy_lib.info_geometry.bregman",
    "holonomy_lib.info_geometry.fisher",
    "holonomy_lib.manifolds.fixed_rank",
    "holonomy_lib.manifolds.spd",
    "holonomy_lib.optimization.sgd",
    "holonomy_lib.simplicial.complex",
    "holonomy_lib.topology.hodge",
    "holonomy_lib.topology.persistent_homology",
    "holonomy_lib.sheaf.laplacian",
    "holonomy_lib.lie.so3",
    "holonomy_lib.lie.spherical_harmonics",
)
for _mod in _OP_MODULES:
    try:
        importlib.import_module(_mod)
    except ImportError:
        # Optional / not-yet-installed modules — skip silently so the
        # server still starts on partial installs.
        pass

try:
    from mcp.server.fastmcp import FastMCP
except ImportError as e:
    raise ImportError(
        "holonomy_lib.provenance.mcp requires the `mcp` package. "
        "Install it via `pip install 'holonomy-lib[mcp]'`."
    ) from e


def _bind_registry(spec: agent.ToolSpec, registry: ProvenanceRegistry):
    """Build a closure that pre-binds the registry arg so the LLM-facing
    surface doesn't see it.

    Preserves the original function's signature *without* the registry
    parameter, so FastMCP can introspect it and generate the right
    tool schema. Annotations are substituted with the resolved type
    hints (from ToolSpec.type_hints) so pydantic — which FastMCP uses
    under the hood — can build models from `from __future__ import
    annotations` modules without trying to eval string annotations
    in the wrong scope.

    Only pre-binds the registry when the wrapped function actually
    declares a `registry` parameter. Some tools (op_docstring) query
    global state and don't take a registry; pre-binding would cause
    a "multiple values for argument" collision.

    Also wraps list-returning tools in a `{"results": [...]}` dict so
    FastMCP serializes them as a single JSON content item instead of
    splitting into one content[i] per element — the LLM-facing shape
    is more consistent that way.
    """
    fn = spec.fn
    sig = inspect.signature(fn)
    takes_registry = "registry" in sig.parameters
    # Drop the `registry` parameter (if present) and replace stringified
    # annotations with resolved types.
    params = []
    for name, p in sig.parameters.items():
        if name == "registry":
            continue
        resolved = spec.type_hints.get(name, p.annotation)
        params.append(p.replace(annotation=resolved))
    # All wrapped tools return dict[str, Any] from the transport's
    # point of view: list returns are wrapped into {"results": [...]},
    # dict returns pass through. Declaring a uniform return type
    # avoids pydantic-validation failures when we wrap a list-typed
    # function's output.
    return_annotation = dict
    bound_sig = sig.replace(
        parameters=params, return_annotation=return_annotation,
    )

    @wraps(fn)
    def wrapper(*args, **kwargs):
        if takes_registry:
            result = fn(registry, *args, **kwargs)
        else:
            result = fn(*args, **kwargs)
        # Wrap bare list returns in a results-keyed dict so FastMCP
        # serializes a single JSON content item instead of one per
        # list element. Python callers (test_agent.py, native tool-use)
        # still see the underlying list via the unwrapped function;
        # this normalization is transport-only.
        if isinstance(result, list):
            return {"results": result}
        return result
    wrapper.__signature__ = bound_sig  # type: ignore[attr-defined]
    wrapper.__annotations__ = {
        p.name: p.annotation for p in params
    }
    wrapper.__annotations__["return"] = return_annotation
    wrapper.__doc__ = spec.docstring or spec.description
    wrapper.__name__ = spec.name
    return wrapper


def build_server(registry: ProvenanceRegistry) -> FastMCP:
    """Construct an MCP server bound to the given registry.

    Registers every tool from `agent.list_tools()` with FastMCP,
    pre-binding the registry argument. The registry is captured by
    closure; reloading requires building a new server.
    """
    server = FastMCP("holonomy-lib-provenance")
    for spec in agent.list_tools():
        bound = _bind_registry(spec, registry)
        # FastMCP's @tool() decorator registers the wrapper; calling it
        # directly is the equivalent of decorating with no args.
        server.tool(description=spec.description)(bound)
    return server


def _load_registry_from_env() -> ProvenanceRegistry:
    """Locate and load the registry pointed to by HOLONOMY_PROVENANCE_REGISTRY."""
    path = os.environ.get("HOLONOMY_PROVENANCE_REGISTRY")
    if not path:
        raise RuntimeError(
            "HOLONOMY_PROVENANCE_REGISTRY environment variable is not set. "
            "Point it at a JSON file written by ProvenanceRegistry.save() "
            "before starting the MCP server."
        )
    p = Path(path).expanduser().resolve()
    if not p.exists():
        raise FileNotFoundError(f"Registry file not found: {p}")
    return ProvenanceRegistry.load(p)


def main() -> None:
    """Entry point: load registry from env and start the stdio server."""
    registry = _load_registry_from_env()
    server = build_server(registry)
    server.run()


if __name__ == "__main__":
    main()
