"""Validation of the graph heat kernel `K_t = exp(-t·L)` via the
two-check methodology — second instance for C7.

The C7 claim is that two *reference-free* consistency checks catch
correctness errors that a "spot-check a few entries against a
reference" approach misses:

  1. **Operator-equation residual**: the heat kernel must satisfy its
     defining evolution equation. For the graph kernel that is the
     linear ODE
         dK/dt + L·K = 0,
     checked by a central finite difference in t against `-L·K`.

  2. **Conserved-quantity check**: the heat semigroup conserves a
     known quantity. For the combinatorial Laplacian `L = D − A`,
     `L·1 = 0`, so `exp(-t·L)·1 = 1` for all t — every row of K_t
     sums to 1, exactly, at every diffusion time.

Neither check needs a known-correct reference kernel. They are
intrinsic to the object. This is the same methodology that caught
the hyperbolic-heat-kernel spectral-shift bug (C1); here we apply it
to a structurally different primitive (discrete operator, ODE
instead of PDE, mass-on-a-graph instead of probability mass on a
manifold) to show it generalizes.

We run it three ways:
  (A) the correct kernel — both checks pass to the FD / machine
      floor.
  (B) a spectral-shift corruption `K → exp(α·t)·K` (the exact shape
      of the C1 bug) — both checks flag it, with a fingerprint that
      pins down α.
  (C) a constant rescale `K → c·K` — the residual is structurally
      *blind* (a scalar multiple of a solution still solves the
      homogeneous ODE `dK/dt = -L·K`), but mass conservation catches
      it.
  (D) a mass-preserving structural perturbation `K → K + ε·L'`
      (L' another Laplacian, so its rows sum to 0) — mass conservation
      is *blind* (row sums unchanged), but the operator residual
      catches it.

(C) and (D) together demonstrate the central C7 point: the two
checks are complementary. Neither alone is a sufficient correctness
gate; each has a blind spot the other covers.

Output: `notes/validation/graph_heat_kernel_results.md`.

Run: PYTHONPATH=. uv run python notes/validation/graph_heat_kernel_validation.py
"""

from __future__ import annotations

from pathlib import Path

import torch

from holonomy_lib.spectral import laplacian
from holonomy_lib.spectral.heat_kernel import heat_kernel_chebyshev


def _make_graph(n: int, seed: int) -> torch.Tensor:
    """A connected random graph's combinatorial Laplacian `L = D − A`.

    Built from a ring (guarantees connectivity) plus random extra
    edges. Combinatorial Laplacian chosen so `L·1 = 0` exactly, giving
    the clean mass-conservation check `K_t·1 = 1`.
    """
    g = torch.Generator().manual_seed(seed)
    A = torch.zeros(n, n, dtype=torch.float64)
    for i in range(n):                       # ring backbone
        j = (i + 1) % n
        A[i, j] = 1.0
        A[j, i] = 1.0
    extra = torch.rand(n, n, generator=g, dtype=torch.float64)
    mask = (extra < 0.15).triu(diagonal=2)   # sparse extra edges
    A = A + (mask + mask.t())
    A = A.clamp(max=1.0)
    return laplacian.combinatorial(A)


def _kernel(L, t, K_cheb, lambda_max, *, shift_alpha=0.0, scale=1.0,
            perturb=None):
    """Graph heat kernel at time t, with optional corruptions:
      shift_alpha: multiply by exp(shift_alpha · t)  (C1-style bug)
      scale:       multiply by a constant            (rescale)
      perturb:     add this fixed matrix             (structural)
    """
    Kt = heat_kernel_chebyshev(L.unsqueeze(0), t=t, K=K_cheb,
                               lambda_max=lambda_max)[0]
    if shift_alpha != 0.0:
        Kt = torch.exp(torch.tensor(shift_alpha * t, dtype=Kt.dtype)) * Kt
    if scale != 1.0:
        Kt = scale * Kt
    if perturb is not None:
        Kt = Kt + perturb
    return Kt


def _ode_residual(L, t, dt, K_cheb, lambda_max, **corruption) -> float:
    """Relative Frobenius residual of `dK/dt + L·K = 0`."""
    K_plus = _kernel(L, t + dt, K_cheb, lambda_max, **corruption)
    K_minus = _kernel(L, t - dt, K_cheb, lambda_max, **corruption)
    dK_dt = (K_plus - K_minus) / (2.0 * dt)
    K_0 = _kernel(L, t, K_cheb, lambda_max, **corruption)
    residual = dK_dt + L @ K_0
    denom = (L @ K_0).norm().item()
    return residual.norm().item() / max(denom, 1e-300)


def _mass_deviation(L, t, K_cheb, lambda_max, **corruption) -> float:
    """Max |row-sum(K_t) − 1| — deviation from mass conservation."""
    Kt = _kernel(L, t, K_cheb, lambda_max, **corruption)
    ones = torch.ones(L.shape[-1], dtype=L.dtype)
    return (Kt @ ones - 1.0).abs().max().item()


def main():
    n = 24
    L = _make_graph(n, seed=7)
    lambda_max = torch.linalg.eigvalsh(L)[-1].item()
    n_edges = int((L.diagonal().sum().item()) / 2)  # sum of degrees / 2
    dt = 1e-3
    K_cheb = 60                                       # well-resolved
    times = [0.25, 0.5, 1.0, 2.0]

    lines = [
        "# Graph heat-kernel validation — C7 methodology, second instance",
        "",
        ("Generated by `notes/validation/graph_heat_kernel_validation.py`. "
         "Applies the two reference-free consistency checks (operator-"
         "equation residual + conserved-quantity check) to the graph "
         "heat kernel `K_t = exp(-t·L)`, demonstrating that the C7 "
         "methodology generalizes from the continuous hyperbolic kernel "
         "(C1) to a discrete graph operator."),
        "",
        f"- Graph: connected random graph, N={n} nodes, {n_edges} edges, "
        f"combinatorial Laplacian `L = D − A` (so `L·1 = 0`).",
        f"- Spectral radius λ_max = {lambda_max:.4f}.",
        f"- Finite-difference step dt = {dt:.0e}; Chebyshev order "
        f"K = {K_cheb}.",
        "",
        "## Check 1 — operator-equation residual `dK/dt + L·K = 0`",
        "",
        ("Central finite difference in t. A correct kernel sits at the "
         "FD truncation floor (`O(dt²)` relative ≈ 1e-6 here)."),
        "",
        "## Check 2 — mass conservation `K_t·1 = 1`",
        "",
        ("`L·1 = 0` ⟹ `exp(-t·L)·1 = 1` exactly. Deviation should be at "
         "machine precision."),
        "",
        "### (A) Correct kernel",
        "",
        "| t | ODE residual (rel) | mass deviation |",
        "|---:|---:|---:|",
    ]
    for t in times:
        res = _ode_residual(L, t, dt, K_cheb, lambda_max)
        mass = _mass_deviation(L, t, K_cheb, lambda_max)
        lines.append(f"| {t:.2f} | {res:.2e} | {mass:.2e} |")

    lines += [
        "",
        ("Both checks pass: ODE residual at the FD floor, mass deviation "
         "at machine precision. The kernel is self-consistent."),
        "",
        "### (B) Negative control — spectral-shift corruption `K → exp(α·t)·K`",
        "",
        ("This is the exact shape of the C1 hyperbolic-kernel bug: a "
         "spurious multiplicative `exp(α·t)` factor. We inject α = 0.1 "
         "and re-run both checks. The corruption is *invisible* to a "
         "single-time spot check (the matrix still looks like a "
         "plausible diffusion operator), but both consistency checks "
         "catch it:"),
        "",
        "| t | ODE residual (rel) | mass deviation | exp(αt)−1 (predicted) |",
        "|---:|---:|---:|---:|",
    ]
    alpha = 0.1
    import math
    for t in times:
        res = _ode_residual(L, t, dt, K_cheb, lambda_max, shift_alpha=alpha)
        mass = _mass_deviation(L, t, K_cheb, lambda_max, shift_alpha=alpha)
        lines.append(
            f"| {t:.2f} | {res:.3e} | {mass:.3e} | "
            f"{math.exp(alpha * t) - 1:.3e} |"
        )

    lines += [
        "",
        ("The mass deviation lands *exactly* on `exp(α·t) − 1` — a "
         "clean numerical fingerprint that both identifies the bug AND "
         "pins down its parameter. The same fingerprint structure "
         "(`naive = exp(c·t)·correct`) is what nailed the C1 spectral-"
         "shift factor. The ODE residual also fires (it grows with t "
         "because the spurious `exp(α·t)` makes `dK/dt` pick up an "
         "extra `α·K` term). Both checks catch this one — redundant "
         "coverage."),
        "",
        "### (C) Complementarity I — constant rescale `K → c·K` (residual blind)",
        "",
        ("A constant scalar multiple of a solution to the *homogeneous* "
         "ODE `dK/dt = −L·K` is still a solution: `d(c·K)/dt + L·(c·K) "
         "= c·(dK/dt + L·K) = 0`. So the operator residual is "
         "**structurally blind** to a constant rescale. Mass "
         "conservation is not — it sees `c·K·1 = c·1`."),
        "",
        "| c (scale) | ODE residual at t=1.0 | mass deviation at t=1.0 | predicted abs(c−1) |",
        "|---:|---:|---:|---:|",
    ]
    for c in [0.5, 0.9, 1.1, 1.5]:
        res = _ode_residual(L, 1.0, dt, K_cheb, lambda_max, scale=c)
        mass = _mass_deviation(L, 1.0, K_cheb, lambda_max, scale=c)
        lines.append(f"| {c:.1f} | {res:.2e} | {mass:.3e} | {abs(c-1):.1f} |")

    # Build a second Laplacian for the mass-preserving perturbation.
    L2 = _make_graph(n, seed=99)
    lines += [
        "",
        ("The residual stays at the FD floor for every c — it cannot "
         "see the scale. Mass deviation reads off `|c − 1|` directly. "
         "**Mass conservation is necessary.**"),
        "",
        "### (D) Complementarity II — mass-preserving perturbation `K → K + ε·L'` (mass blind)",
        "",
        ("Add `ε` times another graph Laplacian `L'`. Since every "
         "Laplacian has zero row sums (`L'·1 = 0`), the perturbed "
         "kernel still conserves mass: `(K + ε·L')·1 = 1`. Mass "
         "conservation is **blind**. But `K + ε·L'` no longer solves "
         "the heat ODE for `L`, so the operator residual fires."),
        "",
        "| ε | ODE residual at t=1.0 | mass deviation at t=1.0 |",
        "|---:|---:|---:|",
    ]
    for eps in [1e-3, 1e-2, 1e-1]:
        pert = eps * L2
        res = _ode_residual(L, 1.0, dt, K_cheb, lambda_max, perturb=pert)
        mass = _mass_deviation(L, 1.0, K_cheb, lambda_max, perturb=pert)
        lines.append(f"| {eps:.0e} | {res:.3e} | {mass:.2e} |")

    lines += [
        "",
        ("The mass deviation stays at machine precision for every ε — "
         "it cannot see the structural perturbation. The residual "
         "scales linearly with ε, catching it. **The operator residual "
         "is necessary.**"),
        "",
        "## Conclusion",
        "",
        ("The two-check methodology transfers cleanly from the "
         "continuous hyperbolic heat kernel (C1: PDE residual + "
         "probability mass on H^n) to the discrete graph heat kernel "
         "(ODE residual + mass conservation on a graph). Both checks "
         "are reference-free — they need no known-correct kernel to "
         "compare against, only the object's own defining equation and "
         "conservation law."),
        "",
        ("The pair is genuinely **complementary**, not redundant: "
         "(C) shows a constant rescale is invisible to the operator "
         "residual but caught by mass conservation; (D) shows a "
         "mass-preserving structural perturbation is invisible to mass "
         "conservation but caught by the operator residual. Each check "
         "has a blind spot that the other covers. A correctness gate "
         "for any operator-semigroup primitive (heat kernels, "
         "geodesic flows, diffusion operators) should run both."),
    ]

    out_path = Path(__file__).parent / "graph_heat_kernel_results.md"
    out_path.write_text("\n".join(lines) + "\n")
    print(f"Wrote {out_path}")


if __name__ == "__main__":
    main()
